#include <iostream>

#include "monster_generated.h" // This was generated by `flatc`
#include "flatbuffers/flatbuffers.h" // The runtime library for C++

// Simplifies naming in the following examples.
using namespace MyGame::Sample; // Specified in the schema.

int main()
{
	flatbuffers::FlatBufferBuilder builder(1024);

	auto sword = CreateWeapon(builder, builder.CreateString("Sword"), (short)3);
	auto axe = CreateWeapon(builder, builder.CreateString("Axe"), (short)5);

	// Create a std::vector of the offsets we had previous made.
	std::vector<flatbuffers::Offset<Weapon>> weapons_vector;
	weapons_vector.push_back(sword);
	weapons_vector.push_back(axe);

	// Then serialize that std::vector into the buffer and again get an Offset
	// to that vector. Use `auto` here since the full type is long, and it just
	// a "typed" number.
	auto weapons = builder.CreateVector(weapons_vector);

	// Create a `vector` representing the inventory of the Orc. Each number
	// could correspond to an item that can be claimed after he is slain.
	unsigned char treasure[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
	auto inventory = builder.CreateVector(treasure, 10);

	// Construct an array of two `Vec3` structs.
	Vec3 points[] = { Vec3(1.0f, 2.0f, 3.0f), Vec3(4.0f, 5.0f, 6.0f) };

	// Serialize it as a vector of structs.
	auto path = builder.CreateVectorOfStructs(points, 2);

	// Create the remaining data needed for the Monster.
	auto name = builder.CreateString("Orc");

	// Create the position struct
	auto position = Vec3(1.0f, 2.0f, 3.0f);

	// Set his hit points to 300 and his mana to 150.
	int hp = 300;
	int mana = 150;

	// Finally, create the monster using the `CreateMonster` helper function
	// to set all fields.
	//
	// Here we set the union field by using the `.Union()` method of the
	// `Offset<Weapon>` axe we already serialized above. We just have to specify
	// which type of object we put in the union, and do that with the
	// auto-generated `Equipment_Weapon` enum.
	flatbuffers::Offset<Monster> orc =
		CreateMonster(builder, &position, mana, hp, name, inventory,
			Color_Red, weapons, Equipment_Weapon, axe.Union(),
			path);

	// Call `Finish()` to instruct the builder that this monster is complete.
	// You could also call `FinishMonsterBuffer(builder, orc);`
	builder.Finish(orc);

	// This must be called after `Finish()`.
	uint8_t* buf = builder.GetBufferPointer();

	// Returns the size of the buffer that `GetBufferPointer()` points to.
	int size = builder.GetSize();


	//--------------------Network-----------------//

	uint8_t* buffer_pointer = buf;/* the data you just read */;

	// Get a view to the root object inside the buffer.
	auto Netmonster = GetMonster(buffer_pointer);

	auto Nethp = Netmonster->hp();
	auto Netmana = Netmonster->mana();
	auto Netname = Netmonster->name()->c_str();
	auto Netpos = Netmonster->pos();
	auto Netx = Netpos->x();
	auto Nety = Netpos->y();
	auto Netz = Netpos->z();
	auto Netinv = Netmonster->inventory();
	auto Netinv_len = Netinv->size();
	auto Netthird_item = Netinv->Get(8);

	std::cout << (int)Netthird_item << std::endl;

	return 0;
}