// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATCHINGEVENTS_MATCHINGEVENTS_H_
#define FLATBUFFERS_GENERATED_MATCHINGEVENTS_MATCHINGEVENTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace MatchingEvents {

struct UserInfo;
struct UserInfoBuilder;

struct MatchData;
struct MatchDataBuilder;

struct UserInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IDX = 4,
    VT_NAME = 6
  };
  int32_t idx() const {
    return GetField<int32_t>(VT_IDX, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_IDX, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct UserInfoBuilder {
  typedef UserInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_idx(int32_t idx) {
    fbb_.AddElement<int32_t>(UserInfo::VT_IDX, idx, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(UserInfo::VT_NAME, name);
  }
  explicit UserInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserInfo> CreateUserInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t idx = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  UserInfoBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_idx(idx);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UserInfo> CreateUserInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t idx = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return MatchingEvents::CreateUserInfo(
      _fbb,
      idx,
      name__);
}

struct MatchData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MatchDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<MatchingEvents::UserInfo>> *users() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MatchingEvents::UserInfo>> *>(VT_USERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USERS) &&
           verifier.VerifyVector(users()) &&
           verifier.VerifyVectorOfTables(users()) &&
           verifier.EndTable();
  }
};

struct MatchDataBuilder {
  typedef MatchData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_users(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MatchingEvents::UserInfo>>> users) {
    fbb_.AddOffset(MatchData::VT_USERS, users);
  }
  explicit MatchDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MatchData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MatchData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MatchData> CreateMatchData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MatchingEvents::UserInfo>>> users = 0) {
  MatchDataBuilder builder_(_fbb);
  builder_.add_users(users);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MatchData> CreateMatchDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<MatchingEvents::UserInfo>> *users = nullptr) {
  auto users__ = users ? _fbb.CreateVector<::flatbuffers::Offset<MatchingEvents::UserInfo>>(*users) : 0;
  return MatchingEvents::CreateMatchData(
      _fbb,
      users__);
}

inline const MatchingEvents::MatchData *GetMatchData(const void *buf) {
  return ::flatbuffers::GetRoot<MatchingEvents::MatchData>(buf);
}

inline const MatchingEvents::MatchData *GetSizePrefixedMatchData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MatchingEvents::MatchData>(buf);
}

template <bool B = false>
inline bool VerifyMatchDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<MatchingEvents::MatchData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMatchDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<MatchingEvents::MatchData>(nullptr);
}

inline void FinishMatchDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MatchingEvents::MatchData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMatchDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MatchingEvents::MatchData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MatchingEvents

#endif  // FLATBUFFERS_GENERATED_MATCHINGEVENTS_MATCHINGEVENTS_H_
