// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USEREVENTS_USEREVENTS_H_
#define FLATBUFFERS_GENERATED_USEREVENTS_USEREVENTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace UserEvents {

struct ServerLogin;
struct ServerLoginBuilder;

struct ClientLogin;
struct ClientLoginBuilder;

struct EventData;
struct EventDataBuilder;

enum EventType : uint8_t {
  EventType_NONE = 0,
  EventType_ClientLogin = 1,
  EventType_ServerLogin = 2,
  EventType_MIN = EventType_NONE,
  EventType_MAX = EventType_ServerLogin
};

inline const EventType (&EnumValuesEventType())[3] {
  static const EventType values[] = {
    EventType_NONE,
    EventType_ClientLogin,
    EventType_ServerLogin
  };
  return values;
}

inline const char * const *EnumNamesEventType() {
  static const char * const names[4] = {
    "NONE",
    "ClientLogin",
    "ServerLogin",
    nullptr
  };
  return names;
}

inline const char *EnumNameEventType(EventType e) {
  if (::flatbuffers::IsOutRange(e, EventType_NONE, EventType_ServerLogin)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEventType()[index];
}

template<typename T> struct EventTypeTraits {
  static const EventType enum_value = EventType_NONE;
};

template<> struct EventTypeTraits<UserEvents::ClientLogin> {
  static const EventType enum_value = EventType_ClientLogin;
};

template<> struct EventTypeTraits<UserEvents::ServerLogin> {
  static const EventType enum_value = EventType_ServerLogin;
};

template <bool B = false>
bool VerifyEventType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventType type);
template <bool B = false>
bool VerifyEventTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ServerLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USERID = 4,
    VT_PASSWORD = 6
  };
  const ::flatbuffers::String *userid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USERID);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USERID) &&
           verifier.VerifyString(userid()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
};

struct ServerLoginBuilder {
  typedef ServerLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_userid(::flatbuffers::Offset<::flatbuffers::String> userid) {
    fbb_.AddOffset(ServerLogin::VT_USERID, userid);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(ServerLogin::VT_PASSWORD, password);
  }
  explicit ServerLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerLogin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerLogin> CreateServerLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> userid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  ServerLoginBuilder builder_(_fbb);
  builder_.add_password(password);
  builder_.add_userid(userid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ServerLogin> CreateServerLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *userid = nullptr,
    const char *password = nullptr) {
  auto userid__ = userid ? _fbb.CreateString(userid) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return UserEvents::CreateServerLogin(
      _fbb,
      userid__,
      password__);
}

struct ClientLogin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientLoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_SUCCESS = 6,
    VT_MESSAGE = 8
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct ClientLoginBuilder {
  typedef ClientLogin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(ClientLogin::VT_PLAYER_ID, player_id, 0);
  }
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(ClientLogin::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(ClientLogin::VT_MESSAGE, message);
  }
  explicit ClientLoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientLogin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientLogin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientLogin> CreateClientLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    bool success = false,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ClientLoginBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_player_id(player_id);
  builder_.add_success(success);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ClientLogin> CreateClientLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    bool success = false,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return UserEvents::CreateClientLogin(
      _fbb,
      player_id,
      success,
      message__);
}

struct EventData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_DATA_TYPE = 6,
    VT_DATA = 8
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  UserEvents::EventType data_type() const {
    return static_cast<UserEvents::EventType>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const UserEvents::ClientLogin *data_as_ClientLogin() const {
    return data_type() == UserEvents::EventType_ClientLogin ? static_cast<const UserEvents::ClientLogin *>(data()) : nullptr;
  }
  const UserEvents::ServerLogin *data_as_ServerLogin() const {
    return data_type() == UserEvents::EventType_ServerLogin ? static_cast<const UserEvents::ServerLogin *>(data()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyEventType(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const UserEvents::ClientLogin *EventData::data_as<UserEvents::ClientLogin>() const {
  return data_as_ClientLogin();
}

template<> inline const UserEvents::ServerLogin *EventData::data_as<UserEvents::ServerLogin>() const {
  return data_as_ServerLogin();
}

struct EventDataBuilder {
  typedef EventData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(EventData::VT_TIMESTAMP, timestamp, 0);
  }
  void add_data_type(UserEvents::EventType data_type) {
    fbb_.AddElement<uint8_t>(EventData::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(EventData::VT_DATA, data);
  }
  explicit EventDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventData> CreateEventData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    UserEvents::EventType data_type = UserEvents::EventType_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  EventDataBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyEventType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, EventType type) {
  switch (type) {
    case EventType_NONE: {
      return true;
    }
    case EventType_ClientLogin: {
      auto ptr = reinterpret_cast<const UserEvents::ClientLogin *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case EventType_ServerLogin: {
      auto ptr = reinterpret_cast<const UserEvents::ServerLogin *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyEventTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyEventType(
        verifier,  values->Get(i), types->GetEnum<EventType>(i))) {
      return false;
    }
  }
  return true;
}

inline const UserEvents::EventData *GetEventData(const void *buf) {
  return ::flatbuffers::GetRoot<UserEvents::EventData>(buf);
}

inline const UserEvents::EventData *GetSizePrefixedEventData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<UserEvents::EventData>(buf);
}

template <bool B = false>
inline bool VerifyEventDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<UserEvents::EventData>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedEventDataBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<UserEvents::EventData>(nullptr);
}

inline void FinishEventDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<UserEvents::EventData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEventDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<UserEvents::EventData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace UserEvents

#endif  // FLATBUFFERS_GENERATED_USEREVENTS_USEREVENTS_H_
